version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: ~/code
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - run: go get github.com/golang/lint/golint
      - run:
          name: Run linting
          command: cd workspace && make lint
